git:
  diffRenderers:
    - colorArg: always
      command: delta --no-gitconfig --dark --paging=never --line-numbers --file-decoration-style=plain --hunk-header-decoration-style=plain --syntax-theme="Monokai Extended Bright" --minus-style='syntax "#8b0000"' --plus-style='syntax "#006400"'
