# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#bab9b9"

# Title color for boxes
theme[title]="#83999b"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8e9797"

# Background color of selected item in processes box
theme[selected_bg]="#83999b"

# Foreground color of selected item in processes box
theme[selected_fg]="#122729"

# Color of inactive/disabled text
theme[inactive_fg]="#909697"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ae8f7d"

# Cpu box outline color
theme[cpu_box]="#6b7172"

# Memory/disks box outline color
theme[mem_box]="#6b7172"

# Net up/down box outline color
theme[net_box]="#6b7172"

# Processes box outline color
theme[proc_box]="#6b7172"

# Box divider line and small boxes line color
theme[div_line]="#353b3c"

# Temperature graph colors
theme[temp_start]="#8e9797"
theme[temp_mid]="#83999b"
theme[temp_end]="#ff5f52"

# CPU graph colors
theme[cpu_start]="#8e9797"
theme[cpu_mid]="#83999b"
theme[cpu_end]="#ff5f52"

# Mem/Disk free meter
theme[free_start]="#8e9797"
theme[free_mid]=""
theme[free_end]="#333c3c"

# Mem/Disk cached meter
theme[cached_start]="#ae8f7d"
theme[cached_mid]=""
theme[cached_end]="#4c3527"

# Mem/Disk available meter
theme[available_start]="#83999b"
theme[available_mid]=""
theme[available_end]="#293e40"

# Mem/Disk used meter
theme[used_start]="#ff5f52"
theme[used_mid]=""
theme[used_end]="#7b0007"

# Download graph colors
theme[download_start]="#8e9797"
theme[download_mid]="#83999b"
theme[download_end]="#ae8f7d"

# Upload graph colors
theme[upload_start]="#8e9797"
theme[upload_mid]="#83999b"
theme[upload_end]="#ae8f7d"
