# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#b7bab8"

# Title color for boxes
theme[title]="#55a391"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7e9b92"

# Background color of selected item in processes box
theme[selected_bg]="#55a391"

# Foreground color of selected item in processes box
theme[selected_fg]="#002a22"

# Color of inactive/disabled text
theme[inactive_fg]="#8d9793"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d08070"

# Cpu box outline color
theme[cpu_box]="#68726f"

# Memory/disks box outline color
theme[mem_box]="#68726f"

# Net up/down box outline color
theme[net_box]="#68726f"

# Processes box outline color
theme[proc_box]="#68726f"

# Box divider line and small boxes line color
theme[div_line]="#323c39"

# Temperature graph colors
theme[temp_start]="#7e9b92"
theme[temp_mid]="#55a391"
theme[temp_end]="#ff5f52"

# CPU graph colors
theme[cpu_start]="#7e9b92"
theme[cpu_mid]="#55a391"
theme[cpu_end]="#ff5f52"

# Mem/Disk free meter
theme[free_start]="#7e9b92"
theme[free_mid]=""
theme[free_end]="#243f38"

# Mem/Disk cached meter
theme[cached_start]="#d08070"
theme[cached_mid]=""
theme[cached_end]="#62281d"

# Mem/Disk available meter
theme[available_start]="#55a391"
theme[available_mid]=""
theme[available_end]="#004237"

# Mem/Disk used meter
theme[used_start]="#ff5f52"
theme[used_mid]=""
theme[used_end]="#7b0007"

# Download graph colors
theme[download_start]="#7e9b92"
theme[download_mid]="#55a391"
theme[download_end]="#d08070"

# Upload graph colors
theme[upload_start]="#7e9b92"
theme[upload_mid]="#55a391"
theme[upload_end]="#d08070"
