cursor #bab9ba
cursor_text_color #91959a

foreground            #bab9ba
background            #121315
selection_foreground  #121a20
selection_background  #333b42
url_color             #8198aa

color0   #121315
color1   #cc5f80
color2   #55aa5f
color3   #d4cd5f
color4   #728ca1
color5   #2b3f4e
color6   #8198aa
color7   #a7adb2
color8   #75797d
color9   #e58fa9
color10  #84cc8d
color11  #fff9a5
color12  #94aabb
color13  #b7ccdd
color14  #d4e2ed
color15  #f0f3f6
