cursor #c0b8b4
cursor_text_color #a2928a

foreground            #c0b8b4
background            #171310
selection_foreground  #24150c
selection_background  #49362b
url_color             #bb8b6e

color0   #171310
color1   #d76660
color2   #6ebb5d
color3   #e9d269
color4   #b17a59
color5   #562d15
color6   #bb8b6e
color7   #c4bcb8
color8   #7e7875
color9   #fca29d
color10  #a0e091
color11  #ffefa5
color12  #cda085
color13  #f3c7ad
color14  #ffe1cf
color15  #fffaf8
