cursor #bfb8b9
cursor_text_color #9f9296

foreground            #bfb8b9
background            #161214
selection_foreground  #22151b
selection_background  #45363c
url_color             #b28a9b

color0   #161214
color1   #ce5e63
color2   #70b259
color3   #dec464
color4   #a97b8e
color5   #52303e
color6   #b28a9b
color7   #baafb4
color8   #7f777a
color9   #f0969a
color10  #9ed58a
color11  #ffeca5
color12  #c39eae
color13  #e7c3d2
color14  #f9dfea
color15  #fff8fb
