include dank-tabs.conf
include dank-theme.conf
allow_remote_control yes
listen_on unix:/tmp/kitty
window_padding_width 5
hide_window_decorations yes
background_opacity 0.75
font_family JetBrains Maple Mono Light 
font_size 12
remember_window_size no
remember_window_position no
# 启动时全屏
fullscreen yes
confirm_os_window_close 0
shell fish
cursor_trail 12
cursor_trail_decay 0.03 0.2
cursor_trail_start_threshold 0
cursor_shape beam
shell_integration no-cursor

map alt+left previous_tab
map alt+right next_tab

map ctrl+t new_tab
map ctrl+w close_tab
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

map ctrl+shift+s kitten screenshot


# BEGIN_KITTY_THEME
# Kanagawa_dragon
include current-theme.conf
# END_KITTY_THEME
